### ISSUE TITLE
Err: total required when dumping cloudant with -s parameter

### ISSUE THREAD

**Issue by vpease** [nolanlawson/pouchdb-dump-cli#3]
I am having problems with the parameter -s. 
Using it against a cloudant server generates: 
unexpected error
[Error: total required]}
the command that i am using is:
pouchdb-dump http://user:pass@server.cloudant.com -o data.txt -s 50
the command:
pouchdb-dump http://server.cloudant.com -o data.txt -s 50 -u user -p pass
generates the same error

Using the command without the -s worked fine.

Against other servers, -s is working fine.

**Comment by nolanlawson** [comment]
Yeah, it's probably because cloudant uses non-integer seqs. This will be tricky to fix.

**Comment by sagarkm** [comment]
I have the same issue. My Cloudant Db is ~60 MB. If I try the URL directly in the db.load the app crashes dur to OUT OF MEMORY. If I download the file using Cordova File Download Plugin, db.load does not recognize the file path as it is outside of WWW folder. So only option is to split the Cloudant DB into smaller chunks and -s.

As per my understand now the newer CouchDb too uses non-integer seqs so this plugin would face issues with that as well?

**Comment by nolanlawson** [comment]
Yes. For now you may need to replicate from Cloudant to CouchDB 1.x and then dump from that.
