### ISSUE TITLE
German Umlaute not correctly saved on windows 8.1

### ISSUE THREAD

**Issue by barbalex** [nolanlawson/pouchdb-dump-cli#8]
My data is German and contains lots of "Umlaute" (ä, Ä, ö, Ö, ü, Ü and more).

In the resulting file these are changed: for instance "ä" becomes "├ñ".

The resulting file seems to be encoded in UTF-16LE. As far as I can tell, this endoding CAN correctly deal with umlaute. I have no idea why it does not.

I am a bad noob, so if there is something I could have done wrong, I probably have. But I managed to dump the database (not that that was hard...) and I can't imagine what I could have done wrong when doing that.

Could it maybe have something to do with Byte Order? According to this article (https://en.wikipedia.org/wiki/UTF-16#Byte_order_encoding_schemes) windows (which I work on) could get that wrong if the file was saved as UTF-16LE but without BOM. No. After reading that again, LE stands for little endian which Windows uses.

Well, no idea why but it does't work for me.

Update: I tried on OsX and it worked, the Umlaute are correct. So it seems to happen only on Windows.

**Comment by nolanlawson** [comment]
Sorry, I don't have a Windows machine, so I'm not sure how to fix this. :/ I'd accept a pull request, though!

**Comment by barbalex** [comment]
o.k., done

**Comment by nolanlawson** [comment]
fixed in #9 and #10

**Comment by nolanlawson** [comment]
published in 2.0.2

**Comment by barbalex** [comment]
That was my first ever pull request. I'm getting a beer now :-)
Am 25.07.2015 7:41 nachm. schrieb "Nolan Lawson" <notifications@github.com>:

**Comment by nolanlawson** [comment]
Nice!! Thanks a lot for your help. :)
